[features]
seeds = false
skip-lint = false

[programs.devnet]
solotery = "J3GAQ7bG9LyddhPDFH9hNQeko9JWhddNx66cRJmDqhKT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/dcsyiqu/test_key_solana.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/createLotery.ts"
request = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/requestTicket.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"